/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class warrenfalk_fuselaj_Fuselaj */

#ifndef _Included_warrenfalk_fuselaj_Fuselaj
#define _Included_warrenfalk_fuselaj_Fuselaj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     warrenfalk_fuselaj_Fuselaj
 * Method:    initialize
 * Signature: (Lwarrenfalk/fuselaj/Filesystem;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_warrenfalk_fuselaj_Fuselaj_initialize
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     warrenfalk_fuselaj_Fuselaj
 * Method:    getCurrentPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_warrenfalk_fuselaj_Fuselaj_getCurrentPath
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
